In [1]:
import numpy as np

In [2]:
# EXERCICIO 1


def media(n):
    soma = 0
    for pos in range(len(n)):
        soma += n[pos]
    res = soma/len(n)
    return res

        
x = np.array([1,2,3,4,5,6,7])
media(x)

4.0

In [3]:
# EXERCICIO 2: criar um array de inteiros de 32 bits 
#de formato (3,2,5), onde todos os elementos são iguais a 3.


a = np.zeros((30), dtype = 'int32')

for i in range(len(a)):
    a[i] = 3
    

a.shape=(3,2,5)
a


array([[[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]]])

In [4]:
# EXERCICIO 3
def s(a,b,n):
    
    
    x=np.arange(a,b,n)
    
    y=np.zeros(len(x))
    
    for i in range(len(x)):
        
        y[i] = (x[i]**2)-9
        
    return x,y


print(s(10, 50, 10))




(array([10, 20, 30, 40]), array([  91.,  391.,  891., 1591.]))


In [5]:
# EXERCICIO 4
def gera_matriz(a,b,n,m):
    
    if m*m == n:
        x = np.linspace(a,b,n)
        y =  np.array(x)
        y.shape=(m,m)
    
        return y
    else:
        print("Não é possível construir")

print(gera_matriz(0, 10, 16, 4))




[[ 0.          0.66666667  1.33333333  2.        ]
 [ 2.66666667  3.33333333  4.          4.66666667]
 [ 5.33333333  6.          6.66666667  7.33333333]
 [ 8.          8.66666667  9.33333333 10.        ]]


In [6]:
# EXERCICIO 5

def linha(m,i):
    
    for j in range(len(m)-1):
        if len(m[j]) != len(m[j-1]):
            print('Não matriz')
            break
    
    else:
        x = m[:,0]
        
        if i >= len(x): #tamanho da linha
            print('Linha não existe')
        else:
            x = m[i,:]
            print(x)
            
def coluna(m,i):
    
    for j in range(len(m)-1):
        if len(m[j]) != len(m[j-1]):
            print('Não matriz')
            break
    
    else:
        x = m[0,:]

        if i >= len(x): #tamanho da coluna
            print('Coluna não existe')
        else:
            x = m[:,i]
            print(x)
        
m = np.array([[1,2], [3,4],[5,6]])
linha(m,0)
coluna(m,0)












[1 2]
[1 3 5]


In [7]:
# EXERCICIO 6

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize = (10,5))

x = np.array([1,2,3,4,5,6])

def f(x):
    
    # f(x) = xˆ3 - xˆ2 + 1
    
    return ((x**3) - (x**2)) + 1


ax.plot(x,f(x))



plt.show()




<Figure size 1000x500 with 1 Axes>